/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyekakhirbasdat;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Isuraa
 */
public class TabelSepeda extends javax.swing.JFrame {

    /**
     * Creates new form Tabel
     */
    public TabelSepeda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    DefaultTableModel tableModel = new DefaultTableModel(
    new Object [][] {

    },
    new String [] {
        "ID Sepeda", "Nama Sepeda", "Harga Beli"
    }
    );
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfNIM = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfJenisKelamin = new javax.swing.JTextField();
        btnShowAll = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        btnRetrieve = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMahasiswa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("ID Sepeda");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nama Sepeda");

        tfNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Harga Beli");

        btnShowAll.setText("SHOW ALL");
        btnShowAll.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                btnShowAllCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        btnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllActionPerformed(evt);
            }
        });

        btnCreate.setText("CREATE");
        btnCreate.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                btnCreateCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnRetrieve.setText("RETRIEVE");
        btnRetrieve.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                btnRetrieveCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        btnRetrieve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrieveActionPerformed(evt);
            }
        });

        btnDelete.setText("DELETE");
        btnDelete.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                btnDeleteCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setText("UPDATE");
        btnUpdate.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                btnUpdateCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        tabelMahasiswa.setModel(tableModel);
        tabelMahasiswa.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelMahasiswa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRetrieve, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(tfNIM)
                    .addComponent(tfNama)
                    .addComponent(tfJenisKelamin)
                    .addComponent(btnShowAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnShowAll)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCreate)
                            .addComponent(btnRetrieve))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDelete)
                            .addComponent(btnUpdate))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowAllCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_btnShowAllCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowAllCaretPositionChanged

    private void btnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllActionPerformed
        tableModel.setRowCount(0);
        showAllData();
    }//GEN-LAST:event_btnShowAllActionPerformed

    private void btnCreateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_btnCreateCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateCaretPositionChanged

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
//        tableModel.setRowCount(0);
//        String nim = tfNIM.getText();
//        String nama = tfNama.getText();
//        String jenisKelamin = tfJenisKelamin.getText();
//
//        try {
//            Connection connection = ConnectionDB.getConnection();
//            statementInsert(connection, nim, nama, jenisKelamin);
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(rootPane, "Gagal menambahkan data BTN");
//        }
//
//        tfNIM.setText("");
//        tfNama.setText("");
//        tfJenisKelamin.setText("");
//        showAllData();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnRetrieveCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_btnRetrieveCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetrieveCaretPositionChanged

    private void btnRetrieveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrieveActionPerformed
//        tableModel.setRowCount(0);
//        try {
//            Connection conn = ConnectionDB.getConnection();
//            ResultSet hasil = statementQuery(conn);
//            while (hasil.next()) {
//                String NIM = hasil.getString("NIM");
//                String nama = hasil.getString("Nama");
//                String jenisKelamin = hasil.getString("JenisKelamin");
//
//                tableModel.addRow(new Object[]{NIM, nama, jenisKelamin});
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(rootPane, "Gagal mengambil data");
//        }

                  tableModel.setRowCount(0);


          if (!(tfNIM.getText().isBlank()&&tfNama.getText().isBlank()&&tfJenisKelamin.getText().isBlank())){
          
                try {
                                Connection conn = ConnectionDB.getConnection();

                    showSomeData( statementQueryCondition(conn, tfNIM.getText(), tfNama.getText(), tfJenisKelamin.getText()) );
                } catch (SQLException ex) {
                    Logger.getLogger(TabelSepeda.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                  Logger.getLogger(TabelSepeda.class.getName()).log(Level.SEVERE, null, ex);
              }
          }
         

    }//GEN-LAST:event_btnRetrieveActionPerformed

    private void btnDeleteCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_btnDeleteCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteCaretPositionChanged

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
//        int selected = tabelMahasiswa.getSelectedRow();
//        Connection conn = null;
//
//        String nim = tabelMahasiswa.getValueAt(selected, 0).toString();
//
//        try {
//            conn = ConnectionDB.getConnection();
//            statementDelete(conn, nim);
//
//            tableModel.setRowCount(0);
//            showAllData();
//
//            tfNIM.setText("");
//            tfNama.setText("");
//            tfJenisKelamin.setText("");
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(rootPane, "SQL");
//        } catch (ClassNotFoundException e) {
//            JOptionPane.showMessageDialog(rootPane, "CLASS NOT FOUND");
//        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_btnUpdateCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateCaretPositionChanged

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
//        try {
//            Connection conn = ConnectionDB.getConnection();
//            statementUpdate(conn);
//
//            tableModel.setRowCount(0);
//            showAllData();
//
//            tfNIM.setText("");
//            tfNama.setText("");
//            tfJenisKelamin.setText("");
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(rootPane, "Gagal melakukan UPDATE terhadap database");
//        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tfNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaActionPerformed

    // RETRIEVE ALL
    public ResultSet statementQueryAll(Connection conn) throws SQLException {
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(
            "SELECT * FROM Sepeda"
        );
        
        return rs;
    }
    
    public ResultSet statementQueryCondition(Connection conn,String id,String nama, String harga) throws SQLException {
       
        
        String sql = "select * from sepeda where Sepeda_ID like ? and Nama_Sepeda like ?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, "%"+id+"%");
        ps.setString(2, "%"+nama+"%");

        ResultSet rs = ps.executeQuery();
        
        return rs;
    }
    
    // SHOW ALL DATA
    public void showAllData() {
        try {
            Connection conn = ConnectionDB.getConnection();
                        JOptionPane.showMessageDialog(rootPane, "CON");

            JOptionPane.showMessageDialog(rootPane, "MIAW");
            ResultSet hasil = statementQueryAll(conn);
            while (hasil.next()) {
                String id = hasil.getString("Sepeda_ID");
                String nama = hasil.getString("Nama_Sepeda");
                String harga_beli = hasil.getString("Harga_Beli");
                
                tableModel.addRow(new Object[]{id, nama, harga_beli});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Gagal menampilkan data : "+ e.getMessage());
        }
    }
    
    
    public void showSomeData(ResultSet hasil) {
        try {
           
            while (hasil.next()) {
                String id = hasil.getString("Sepeda_ID");
                String nama = hasil.getString("Nama_Sepeda");
                String harga_beli = hasil.getString("Harga_Beli");
                
                tableModel.addRow(new Object[]{id, nama, harga_beli});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Gagal menampilkan data : "+ e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelSepeda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelSepeda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelSepeda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelSepeda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelSepeda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRetrieve;
    private javax.swing.JButton btnShowAll;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelMahasiswa;
    private javax.swing.JTextField tfJenisKelamin;
    private javax.swing.JTextField tfNIM;
    private javax.swing.JTextField tfNama;
    // End of variables declaration//GEN-END:variables
}
