/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyekakhirbasdat;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Isuraa
 */
public class TabelSepeda extends javax.swing.JFrame {

    /**
     * Creates new form Tabel
     */
    public TabelSepeda() {
        initComponents();
        showAllData();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    DefaultTableModel tableModel = new DefaultTableModel(
    new Object [][] {

    },
    new String [] {
        "ID Sepeda", "Nama Sepeda", "Harga Beli"
    }
    );
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfIDSepeda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfNamaSepeda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfHargaBeli = new javax.swing.JTextField();
        btnShowAll = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        btnRetrieve = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelSepeda = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("ID Sepeda");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nama Sepeda");

        tfNamaSepeda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaSepedaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Harga Beli");

        btnShowAll.setText("CLEAR");
        btnShowAll.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                btnShowAllCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        btnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllActionPerformed(evt);
            }
        });

        btnCreate.setText("CREATE");
        btnCreate.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                btnCreateCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnRetrieve.setText("RETRIEVE");
        btnRetrieve.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                btnRetrieveCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        btnRetrieve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrieveActionPerformed(evt);
            }
        });

        btnDelete.setText("DELETE");
        btnDelete.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                btnDeleteCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setText("UPDATE");
        btnUpdate.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                btnUpdateCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        tabelSepeda.setModel(tableModel);
        tabelSepeda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = tabelSepeda.getSelectedRow();

                if (row != -1) {
                    String idSepeda = tabelSepeda.getValueAt(row, 0).toString(); // Kolom ke-0
                    String namaSepeda = tabelSepeda.getValueAt(row, 1).toString(); // Kolom ke-1
                    String hargaBeli = tabelSepeda.getValueAt(row, 2).toString(); // Kolom ke-1

                    tfIDSepeda.setEnabled(false);
                    tfIDSepeda.setText(idSepeda);
                    tfNamaSepeda.setText(namaSepeda);
                    tfHargaBeli.setText(hargaBeli);
                }
            }
        });
        tabelSepeda.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelSepeda);

        jButton1.setText("Back to Lobby");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRetrieve, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(tfIDSepeda)
                            .addComponent(tfNamaSepeda)
                            .addComponent(tfHargaBeli)
                            .addComponent(btnShowAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfIDSepeda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNamaSepeda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnShowAll)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCreate)
                            .addComponent(btnRetrieve))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDelete)
                            .addComponent(btnUpdate))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowAllCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_btnShowAllCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowAllCaretPositionChanged

    private void btnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllActionPerformed
        tableModel.setRowCount(0);
        showAllData();
    }//GEN-LAST:event_btnShowAllActionPerformed

    private void btnCreateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_btnCreateCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateCaretPositionChanged

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        tableModel.setRowCount(0);
        String idSepeda = tfIDSepeda.getText();
        String namaSepeda = tfNamaSepeda.getText();
        int hargaBeli = Integer.parseInt(tfHargaBeli.getText());

        try {
            Connection connection = ConnectionDB.getConnection();
            statementInsert(connection, idSepeda, namaSepeda, hargaBeli);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Gagal menambahkan data");
        }

        tfIDSepeda.setText("");
        tfNamaSepeda.setText("");
        tfHargaBeli.setText("");
        showAllData();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnRetrieveCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_btnRetrieveCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetrieveCaretPositionChanged

    private void btnRetrieveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrieveActionPerformed
//        tableModel.setRowCount(0);
//        try {
//            Connection conn = ConnectionDB.getConnection();
//            ResultSet hasil = statementQuery(conn);
//            while (hasil.next()) {
//                String NIM = hasil.getString("NIM");
//                String nama = hasil.getString("Nama");
//                String jenisKelamin = hasil.getString("JenisKelamin");
//
//                tableModel.addRow(new Object[]{NIM, nama, jenisKelamin});
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(rootPane, "Gagal mengambil data");
//        }

                  tableModel.setRowCount(0);


          if (!(tfIDSepeda.getText().isBlank()&&tfNamaSepeda.getText().isBlank()&&tfHargaBeli.getText().isBlank())){
          
                try {
                    Connection conn = ConnectionDB.getConnection();
                    showSomeData( statementQueryCondition(conn, tfIDSepeda.getText(), tfNamaSepeda.getText(), tfHargaBeli.getText()) );
                } catch (SQLException ex) {
                    Logger.getLogger(TabelSepeda.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                  Logger.getLogger(TabelSepeda.class.getName()).log(Level.SEVERE, null, ex);
              }
          }
         

    }//GEN-LAST:event_btnRetrieveActionPerformed

    private void btnDeleteCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_btnDeleteCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteCaretPositionChanged

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
        
        int selected = tabelSepeda.getSelectedRow();
        Connection conn = null;

        String idSepeda = tabelSepeda.getValueAt(selected, 0).toString();

        try {
            conn = ConnectionDB.getConnection();
            statementDelete(conn, idSepeda);

            tableModel.setRowCount(0);
            showAllData();

            tfIDSepeda.setText("");
            tfNamaSepeda.setText("");
            tfHargaBeli.setText("");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "SQL");
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(rootPane, "CLASS NOT FOUND");
        }
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_btnUpdateCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateCaretPositionChanged

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            Connection conn = ConnectionDB.getConnection();
            statementUpdate(conn);

            tableModel.setRowCount(0);
            showAllData();

            tfIDSepeda.setText("");
            tfNamaSepeda.setText("");
            tfHargaBeli.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Gagal melakukan UPDATE terhadap database");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tfNamaSepedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaSepedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaSepedaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Lobby newWindow = new Lobby();
        this.dispose();
        newWindow.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

        // CREATE
    public void statementInsert(Connection conn, String idSepeda, String namaSepeda, double hargaSepeda) throws SQLException {
        String format = ("insert into Sepeda(Sepeda_ID,Nama_Sepeda,Harga_Beli) values ('" + idSepeda + "','" + namaSepeda + "'," + hargaSepeda +")");
        Statement st = conn.createStatement();
        st.executeUpdate(format);
    }
    
    // RETRIEVE ALL
    public ResultSet statementQueryAll(Connection conn) throws SQLException {
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(
            "SELECT * FROM Sepeda"
        );
        
        return rs;
    }
    
    public ResultSet statementQueryCondition(Connection conn,String id,String nama, String harga) throws SQLException {
        String sql = "select * from sepeda where Sepeda_ID like ? and Nama_Sepeda like ?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, "%"+id+"%");
        ps.setString(2, "%"+nama+"%");

        ResultSet rs = ps.executeQuery();
        
        return rs;
    }
    
    // SHOW ALL DATA
    public void showAllData() {
        try {
            Connection conn = ConnectionDB.getConnection();

            tfIDSepeda.setEnabled(true);
            tfIDSepeda.setText("");
            tfNamaSepeda.setText("");
            tfHargaBeli.setText("");
            
            ResultSet hasil = statementQueryAll(conn);
            while (hasil.next()) {
                String id = hasil.getString("Sepeda_ID");
                String nama = hasil.getString("Nama_Sepeda");
                String harga_beli = hasil.getString("Harga_Beli");
                
                tableModel.addRow(new Object[]{id, nama, harga_beli});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Gagal menampilkan data : "+ e.getMessage());
        }
    }
    
    // UPDATE
    public void statementUpdate(Connection conn) throws SQLException {
        int selected = tabelSepeda.getSelectedRow();
        
        String idSepedaTerpilih = tabelSepeda.getValueAt(selected, 0).toString(); // kolom idSEPEDA
        
        String idSepedaBaru = tfIDSepeda.getText();
        String namaSepedaBaru = tfNamaSepeda.getText();
        int hargaSepedaBaru = Integer.parseInt(tfHargaBeli.getText());

        String format = "UPDATE Sepeda SET Sepeda_ID = '" + idSepedaBaru + "', Nama_Sepeda = '" + namaSepedaBaru + "', Harga_Beli = " + hargaSepedaBaru + " WHERE Sepeda_ID = '" + idSepedaTerpilih + "'";
        Statement st = conn.createStatement();
        st.executeUpdate(format);
    }
    
    // DELETE
    public void statementDelete(Connection conn, String idSepeda)throws SQLException{
        try {
            Statement st = conn.createStatement();
            if (idSepeda == null) {
                idSepeda = "";
            }
            st.executeUpdate("delete from Sepeda where Sepeda_ID = " + idSepeda);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "Gagal untuk menghapus data");
        }
    }
    
    
    public void showSomeData(ResultSet hasil) {
        try {
           
            while (hasil.next()) {
                String id = hasil.getString("Sepeda_ID");
                String nama = hasil.getString("Nama_Sepeda");
                String harga_beli = hasil.getString("Harga_Beli");
                
                tableModel.addRow(new Object[]{id, nama, harga_beli});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Gagal menampilkan data : "+ e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelSepeda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelSepeda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelSepeda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelSepeda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelSepeda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRetrieve;
    private javax.swing.JButton btnShowAll;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelSepeda;
    private javax.swing.JTextField tfHargaBeli;
    private javax.swing.JTextField tfIDSepeda;
    private javax.swing.JTextField tfNamaSepeda;
    // End of variables declaration//GEN-END:variables
}
